name: moviereviewapp
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.2
  http: ^0.13.3
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.0.9
  build_runner: ^2.0.4
  bloc_test: ^8.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/movie_reel.png

  fonts:
    - family: CFParis
      fonts:
        - asset: fonts/CFParis-Regular.ttf
